import type { GameState } from "@/types/game";

export type CloudGameState = Pick<
  GameState,
  | "gold"
  | "streak"
  | "strengthXP"
  | "agilityXP"
  | "intelligenceXP"
  | "habits"
  | "lastCompletionDate"
  | "allCompletedToday"
  | "dungeonKeys"
  | "tasksCompletedToday"
  | "goldFromStandardTasksToday"
  | "lastEconomyResetDate"
  | "firstDungeonKeyDroppedToday"
  | "sageEpicQuestClaimedToday"
  | "sageEpicQuestId"
  | "sageEpicQuestDate"
  | "sageEpicRerollsUsedToday"
  | "sageEpicRerollPendingIds"
  | "lastMorningGoldClaimDate"
  | "unlockedTitleIds"
  | "habitCompletionLog"
  | "completedStrengthQuests"
  | "completedAgilityQuests"
  | "completedIntelligenceQuests"
  | "ownedItemIds"
  | "equippedOutfitId"
  | "equippedRelicId"
  | "activeDragonId"
  | "dragonSwitchCooldownUntil"
  | "consumables"
  | "activityByDate"
  | "completedHabitNamesByDate"
  | "hapticsEnabled"
  | "sageFocus"
  | "sageChatMessages"
  | "planningDayOrderByDate"
  | "castleQuestSortMode"
  | "castleQuestOrderIds"
  | "heroDisplayName"
  | "heroGender"
  | "onboardingWeakness"
  | "onboardingCommitment"
  | "onboardingEnergyBaseline"
  | "onboardingScreenDistraction"
  | "onboardingStressResponse"
  | "onboardingPhysicality"
  | "onboardingPlanningStyle"
  | "onboardingComplete"
  | "reflectionSavedDateKeys"
  | "heroShopPurchaseEver"
  | "heroDailyQuestClaimsDate"
  | "heroDailyQuestClaimedIds"
  | "heroEpicMilestoneClaimedIds"
>;

export function pickCloudGameState(state: GameState): CloudGameState {
  return {
    gold: state.gold,
    streak: state.streak,
    strengthXP: state.strengthXP,
    agilityXP: state.agilityXP,
    intelligenceXP: state.intelligenceXP,
    habits: state.habits,
    lastCompletionDate: state.lastCompletionDate,
    allCompletedToday: state.allCompletedToday,
    dungeonKeys: state.dungeonKeys,
    tasksCompletedToday: state.tasksCompletedToday,
    goldFromStandardTasksToday: state.goldFromStandardTasksToday,
    lastEconomyResetDate: state.lastEconomyResetDate,
    firstDungeonKeyDroppedToday: state.firstDungeonKeyDroppedToday,
    sageEpicQuestClaimedToday: state.sageEpicQuestClaimedToday,
    sageEpicQuestId: state.sageEpicQuestId,
    sageEpicQuestDate: state.sageEpicQuestDate,
    sageEpicRerollsUsedToday: state.sageEpicRerollsUsedToday,
    sageEpicRerollPendingIds: state.sageEpicRerollPendingIds,
    lastMorningGoldClaimDate: state.lastMorningGoldClaimDate,
    unlockedTitleIds: state.unlockedTitleIds,
    habitCompletionLog: state.habitCompletionLog,
    completedStrengthQuests: state.completedStrengthQuests,
    completedAgilityQuests: state.completedAgilityQuests,
    completedIntelligenceQuests: state.completedIntelligenceQuests,
    ownedItemIds: state.ownedItemIds,
    equippedOutfitId: state.equippedOutfitId,
    equippedRelicId: state.equippedRelicId,
    activeDragonId: state.activeDragonId,
    dragonSwitchCooldownUntil: state.dragonSwitchCooldownUntil,
    consumables: state.consumables,
    activityByDate: state.activityByDate,
    completedHabitNamesByDate: state.completedHabitNamesByDate,
    hapticsEnabled: state.hapticsEnabled,
    sageFocus: state.sageFocus,
    sageChatMessages: state.sageChatMessages,
    planningDayOrderByDate: state.planningDayOrderByDate,
    castleQuestSortMode: state.castleQuestSortMode,
    castleQuestOrderIds: state.castleQuestOrderIds,
    heroDisplayName: state.heroDisplayName,
    heroGender: state.heroGender,
    onboardingWeakness: state.onboardingWeakness,
    onboardingCommitment: state.onboardingCommitment,
    onboardingEnergyBaseline: state.onboardingEnergyBaseline,
    onboardingScreenDistraction: state.onboardingScreenDistraction,
    onboardingStressResponse: state.onboardingStressResponse,
    onboardingPhysicality: state.onboardingPhysicality,
    onboardingPlanningStyle: state.onboardingPlanningStyle,
    onboardingComplete: state.onboardingComplete,
    reflectionSavedDateKeys: state.reflectionSavedDateKeys,
    heroShopPurchaseEver: state.heroShopPurchaseEver,
    heroDailyQuestClaimsDate: state.heroDailyQuestClaimsDate,
    heroDailyQuestClaimedIds: state.heroDailyQuestClaimedIds,
    heroEpicMilestoneClaimedIds: state.heroEpicMilestoneClaimedIds,
  };
}

